DROP DATABASE forumDatabase;
CREATE DATABASE IF NOT EXISTS forumDatabase;
USE forumDatabase;

CREATE TABLE IF NOT EXISTS client (
id INT(11) PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(256) NOT NULL,
password VARCHAR(256) NOT NULL,
type VARCHAR(256) DEFAULT 'client' CHECK (type IN ('admin','client')),
banned BOOLEAN DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS topic (
id INT(11) PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(256) NOT NULL,
description VARCHAR(1000) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS post (
id INT(11) PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(256) NOT NULL,
description VARCHAR(1000) NOT NULL,
post_date DATE NOT NULL,
post_time TIME NOT NULL,
client_id INT(11) NOT NULL,
banned BOOLEAN DEFAULT '0',
FOREIGN KEY (client_id) REFERENCES client(id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS topic_post (
id INT(11) PRIMARY KEY AUTO_INCREMENT,
topic_id INT(11) NOT NULL,
post_id INT(11) NOT NULL,
FOREIGN KEY (topic_id) REFERENCES topic(id) ON UPDATE CASCADE,
FOREIGN KEY (post_id) REFERENCES post(id) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS post_comment (
id INT(11) PRIMARY KEY AUTO_INCREMENT,
description VARCHAR(1000) NOT NULL,
post_date DATE NOT NULL,
post_time TIME NOT NULL,
client_id INT(11) NOT NULL,
post_id INT(11) NOT NULL,
banned BOOLEAN DEFAULT '0',
FOREIGN KEY (client_id) REFERENCES client(id) ON UPDATE CASCADE,
FOREIGN KEY (post_id) REFERENCES post(id) ON UPDATE CASCADE
);
